name: test-nbconvert-a11y
channels:
  - conda-forge
  - microsoft
dependencies:
  - python=3.11
  - openjdk
  - pip
  - pip:
    - pytest-playwright
    - pytest-html
    - accessible-pygments
    - requests-cache
    - markdown-it-py[plugins,linkify]
    - python-slugify
    - html5lib
    - build
  - nodejs
  - playwright
  - nbconvert
  - pytest
  - pytest-xdist
  - pytest-sugar
  - matplotlib-base
  - numpy
  - ipywidgets
  - beautifulsoup4
  - scipy
  - doit
  - mkdocs-material
  - mkdocstrings[python]